server:
  port: 9092

spring:
  application:
    name: rocketmq-boot-consumer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

rocketmq:
  name-server: 192.168.1.112:9876
  consumer:
    group: ${spring.application.name}
