server:
  port: 9091

spring:
  application:
    name: rocketmq-boot-producer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

rocketmq:
  name-server: 192.168.1.112:9876
  producer:
    group: ${spring.application.name}
