server:
  port: 8081

spring:
  application:
    name: rocketmq-native-producer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

rocketmq:
  producer:
    # 是否开启生产者配置
    enable: true
    # nameserver地址
    nameserver-address: 192.168.1.112:9876
    # 生产者组
    # 发送同一类消息设置为同一个group，保证唯一
    # 默认RocketMQ会使用ip@pid作为唯一标识
    group-name: ${spring.application.name}
    # 发送消息的最大长度
    # 默认 1024 * 4 = 4M
    max-message-size: 4096
    # 发送消息超时时间
    # 默认 3000
    send-message-time-out: 3000
    # 发送消息失败重试次数
    # 默认 2
    retry-times-when-send-failed: 2
